apiVersion: batch/v1
kind: Job
metadata:
 name: foundryinstaller
 namespace: default
spec:
 template:
   metadata:
     name: foundryinstaller
   spec:
     containers:
     - name: founderinstaller
       image: image-registry.openshift-image-registry.svc:5000/default/kubecf-install
       command: ["/installer/check-ocp-cluster.sh"]
       envFrom:
        - configMapRef:
            name: install-env-list
       env:
          - name: OCP_TOKEN
            valueFrom:
              secretKeyRef:
                name: ocp-token-secret
                key: token
     restartPolicy: OnFailure
