apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: "foundryinstall-app"
  name: foundryinstall-app
  namespace: default
spec:
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
  selector:
    matchLabels:
      app: "foundryinstall"
status: {}

